name: unit-test
on: [push]

jobs:
  tests:
    name: Smart Contract unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Environment
      uses: actions/setup-node@v3
      with:
        node-version: 18.19.1
    - name: Cache node-modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci
    - name: Run tests
      run: npx hardhat test 